-- V16: WHO growth assessment fields.
ALTER TABLE growth_records
    ADD COLUMN IF NOT EXISTS age_in_days INT,
    ADD COLUMN IF NOT EXISTS bmi_for_age_z_score DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS risk_level VARCHAR(20),
    ADD COLUMN IF NOT EXISTS health_score INT,
    ADD COLUMN IF NOT EXISTS growth_trend VARCHAR(20),
    ADD COLUMN IF NOT EXISTS referral_recommended BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS emergency_flag BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS oedema BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS severe_dehydration BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS ai_summary VARCHAR(2000);
