-- V25: Phone verification OTP tokens.
CREATE TABLE IF NOT EXISTS phone_otp_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phone_number VARCHAR(20) NOT NULL,
    code VARCHAR(6) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    used_at TIMESTAMP NULL,
    attempts INT NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_otp_phone ON phone_otp_tokens(phone_number);
CREATE INDEX IF NOT EXISTS idx_otp_code ON phone_otp_tokens(code);
