package com.mtotocare.africa.reports;

import com.lowagie.text.*;
import com.lowagie.text.pdf.PdfPCell;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;
import com.mtotocare.africa.child.Child;
import com.mtotocare.africa.growth.GrowthRecord;
import com.mtotocare.africa.user.User;
import com.mtotocare.africa.vaccination.Vaccination;
import lombok.extern.slf4j.Slf4j;
import org.apache.poi.ss.usermodel.*;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.springframework.stereotype.Service;

import java.io.ByteArrayOutputStream;
import java.time.LocalDate;
import java.time.Period;
import java.time.format.DateTimeFormatter;
import java.util.List;

/**
 * FR-028: Generate vaccination certificates (PDF).
 * FR-069: Export child health reports in PDF.
 * FR-070: Export reports in Excel.
 *
 * Uses OpenPDF for PDF and Apache POI for Excel.
 */
@Slf4j
@Service
public class ReportExportService {

    private static final DateTimeFormatter DATE = DateTimeFormatter.ofPattern("dd MMM yyyy");
    private static final com.lowagie.text.Font TITLE = new com.lowagie.text.Font(com.lowagie.text.Font.HELVETICA, 18, com.lowagie.text.Font.BOLD, new java.awt.Color(46, 125, 50));
    private static final com.lowagie.text.Font H2 = new com.lowagie.text.Font(com.lowagie.text.Font.HELVETICA, 12, com.lowagie.text.Font.BOLD, new java.awt.Color(46, 125, 50));
    private static final com.lowagie.text.Font BODY = new com.lowagie.text.Font(com.lowagie.text.Font.HELVETICA, 10, com.lowagie.text.Font.NORMAL);

    // ============== FR-028: Vaccination certificate ==============
    public byte[] buildVaccinationCertificate(User parent, Child child, List<Vaccination> records) {
        try (ByteArrayOutputStream out = new ByteArrayOutputStream()) {
            Document doc = new Document(PageSize.A4, 50, 50, 50, 50);
            PdfWriter.getInstance(doc, out);
            doc.open();

            Paragraph header = new Paragraph("MTOTOCARE AFRICA", TITLE);
            header.setAlignment(Element.ALIGN_CENTER);
            doc.add(header);

            Paragraph sub = new Paragraph("Vaccination Certificate", H2);
            sub.setAlignment(Element.ALIGN_CENTER);
            doc.add(sub);

            Paragraph space = new Paragraph(" ");
            doc.add(space);

            PdfPTable info = new PdfPTable(2);
            info.setWidthPercentage(100);
            info.addCell(labelCell("Child name"));
            info.addCell(valueCell(child.getFirstName() + " " +
                    (child.getLastName() != null ? child.getLastName() : "")));
            info.addCell(labelCell("Date of birth"));
            info.addCell(valueCell(child.getDateOfBirth() != null ? child.getDateOfBirth().toString() : "—"));
            info.addCell(labelCell("Gender"));
            info.addCell(valueCell(child.getGender() != null ? child.getGender() : "—"));
            info.addCell(labelCell("Blood group"));
            info.addCell(valueCell(child.getBloodGroup() != null ? child.getBloodGroup() : "—"));
            info.addCell(labelCell("Parent / guardian"));
            info.addCell(valueCell(parent.getFullName() + " (" + parent.getEmail() + ")"));
            info.addCell(labelCell("Issued on"));
            info.addCell(valueCell(LocalDate.now().format(DATE)));
            doc.add(info);

            doc.add(space);

            Paragraph title = new Paragraph("Vaccination history", H2);
            doc.add(title);

            if (records == null || records.isEmpty()) {
                doc.add(new Paragraph("No vaccinations recorded.", BODY));
            } else {
                PdfPTable table = new PdfPTable(4);
                table.setWidthPercentage(100);
                table.addCell(headerCell("Vaccine"));
                table.addCell(headerCell("Date"));
                table.addCell(headerCell("Dose"));
                table.addCell(headerCell("Provider"));
                for (Vaccination r : records) {
                    table.addCell(valueCell(r.getVaccineName() != null ? r.getVaccineName() : "—"));
                    table.addCell(valueCell(r.getAdministeredAt() != null ? r.getAdministeredAt().toString() : "—"));
                    table.addCell(valueCell(r.getDoseNumber() != null ? r.getDoseNumber().toString() : "—"));
                    table.addCell(valueCell(r.getAdministeredBy() != null ? r.getAdministeredBy() : "—"));
                }
                doc.add(table);
            }

            doc.add(space);
            Paragraph footer = new Paragraph(
                    "This certificate is generated by MtotoCare Africa and reflects the vaccinations recorded in the system. " +
                            "Please retain for your child's health records.",
                    new com.lowagie.text.Font(com.lowagie.text.Font.HELVETICA, 9, com.lowagie.text.Font.ITALIC, java.awt.Color.GRAY));
            doc.add(footer);

            doc.close();
            return out.toByteArray();
        } catch (Exception e) {
            log.error("Failed to build vaccination certificate", e);
            throw new RuntimeException("Failed to build PDF: " + e.getMessage(), e);
        }
    }

    // ============== FR-069: Child health report (PDF) ==============
    public byte[] buildChildHealthReport(Child child, List<GrowthRecord> growth, List<Vaccination> vaccinations) {
        try (ByteArrayOutputStream out = new ByteArrayOutputStream()) {
            Document doc = new Document(PageSize.A4, 50, 50, 50, 50);
            PdfWriter.getInstance(doc, out);
            doc.open();

            Paragraph t = new Paragraph("Child Health Report", TITLE);
            t.setAlignment(Element.ALIGN_CENTER);
            doc.add(t);
            doc.add(new Paragraph(" "));

            PdfPTable info = new PdfPTable(2);
            info.setWidthPercentage(100);
            info.addCell(labelCell("Name"));
            info.addCell(valueCell(child.getFirstName() + " " +
                    (child.getLastName() != null ? child.getLastName() : "")));
            info.addCell(labelCell("Date of birth"));
            info.addCell(valueCell(child.getDateOfBirth() != null ? child.getDateOfBirth().toString() : "—"));
            info.addCell(labelCell("Age"));
            info.addCell(valueCell(child.getDateOfBirth() != null
                    ? ageString(child.getDateOfBirth()) : "—"));
            info.addCell(labelCell("Gender"));
            info.addCell(valueCell(child.getGender() != null ? child.getGender() : "—"));
            info.addCell(labelCell("Blood group"));
            info.addCell(valueCell(child.getBloodGroup() != null ? child.getBloodGroup() : "—"));
            info.addCell(labelCell("Report date"));
            info.addCell(valueCell(LocalDate.now().format(DATE)));
            doc.add(info);

            doc.add(new Paragraph(" "));
            doc.add(new Paragraph("Growth history", H2));
            if (growth == null || growth.isEmpty()) {
                doc.add(new Paragraph("No growth measurements recorded.", BODY));
            } else {
                PdfPTable t1 = new PdfPTable(3);
                t1.setWidthPercentage(100);
                t1.addCell(headerCell("Date"));
                t1.addCell(headerCell("Weight (kg)"));
                t1.addCell(headerCell("Height (cm)"));
                for (GrowthRecord g : growth) {
                    t1.addCell(valueCell(g.getMeasurementDate() != null ? g.getMeasurementDate().toString() : "—"));
                    t1.addCell(valueCell(g.getWeightKg() != null ? g.getWeightKg().toString() : "—"));
                    t1.addCell(valueCell(g.getHeightCm() != null ? g.getHeightCm().toString() : "—"));
                }
                doc.add(t1);
            }

            doc.add(new Paragraph(" "));
            doc.add(new Paragraph("Vaccination history", H2));
            if (vaccinations == null || vaccinations.isEmpty()) {
                doc.add(new Paragraph("No vaccinations recorded.", BODY));
            } else {
                PdfPTable t2 = new PdfPTable(2);
                t2.setWidthPercentage(100);
                t2.addCell(headerCell("Vaccine"));
                t2.addCell(headerCell("Date"));
                for (Vaccination r : vaccinations) {
                    t2.addCell(valueCell(r.getVaccineName() != null ? r.getVaccineName() : "—"));
                    t2.addCell(valueCell(r.getAdministeredAt() != null ? r.getAdministeredAt().toString() : "—"));
                }
                doc.add(t2);
            }

            doc.close();
            return out.toByteArray();
        } catch (Exception e) {
            log.error("Failed to build child health report", e);
            throw new RuntimeException("Failed to build PDF: " + e.getMessage(), e);
        }
    }

    // ============== FR-070: Excel export ==============
    public byte[] buildChildrenExcel(List<Child> children) {
        try (XSSFWorkbook wb = new XSSFWorkbook();
             ByteArrayOutputStream out = new ByteArrayOutputStream()) {
            org.apache.poi.ss.usermodel.Sheet sheet = wb.createSheet("Children");

            // Header row
            org.apache.poi.ss.usermodel.Row header = sheet.createRow(0);
            org.apache.poi.ss.usermodel.CellStyle headStyle = wb.createCellStyle();
            org.apache.poi.ss.usermodel.Font headFont = wb.createFont();
            headFont.setBold(true);
            headStyle.setFont(headFont);
            headStyle.setFillForegroundColor(IndexedColors.LIGHT_GREEN.getIndex());
            headStyle.setFillPattern(FillPatternType.SOLID_FOREGROUND);

            String[] cols = {"ID", "First name", "Last name", "Date of birth", "Age (months)",
                    "Gender", "Blood group", "Birth weight (kg)", "Birth height (cm)"};
            for (int i = 0; i < cols.length; i++) {
                org.apache.poi.ss.usermodel.Cell c = header.createCell(i);
                c.setCellValue(cols[i]);
                c.setCellStyle(headStyle);
            }

            int rowIdx = 1;
            for (Child c : children) {
                org.apache.poi.ss.usermodel.Row r = sheet.createRow(rowIdx++);
                r.createCell(0).setCellValue(c.getId() != null ? c.getId() : 0);
                r.createCell(1).setCellValue(safe(c.getFirstName()));
                r.createCell(2).setCellValue(safe(c.getLastName()));
                r.createCell(3).setCellValue(c.getDateOfBirth() != null ? c.getDateOfBirth().toString() : "");
                r.createCell(4).setCellValue(ageInMonths(c.getDateOfBirth()));
                r.createCell(5).setCellValue(c.getGender() != null ? c.getGender() : "");
                r.createCell(6).setCellValue(safe(c.getBloodGroup()));
                r.createCell(7).setCellValue(c.getBirthWeightKg() != null ? c.getBirthWeightKg() : 0);
                r.createCell(8).setCellValue(c.getBirthHeightCm() != null ? c.getBirthHeightCm() : 0);
            }

            // Auto-size columns
            for (int i = 0; i < cols.length; i++) sheet.autoSizeColumn(i);

            wb.write(out);
            return out.toByteArray();
        } catch (Exception e) {
            log.error("Failed to build Excel", e);
            throw new RuntimeException("Failed to build Excel: " + e.getMessage(), e);
        }
    }

    // ============ Helpers ============
    private static PdfPCell labelCell(String text) {
        PdfPCell c = new PdfPCell(new Phrase(text, H2));
        c.setBackgroundColor(new java.awt.Color(232, 245, 233));
        c.setPadding(6);
        return c;
    }

    private static PdfPCell valueCell(String text) {
        PdfPCell c = new PdfPCell(new Phrase(text == null ? "—" : text, BODY));
        c.setPadding(6);
        return c;
    }

    private static PdfPCell headerCell(String text) {
        PdfPCell c = new PdfPCell(new Phrase(text, H2));
        c.setBackgroundColor(new java.awt.Color(46, 125, 50));
        c.setHorizontalAlignment(Element.ALIGN_CENTER);
        c.setPadding(6);
        return c;
    }

    private static String safe(String s) {
        return s == null ? "" : s;
    }

    private static String ageString(LocalDate dob) {
        if (dob == null) return "—";
        Period p = Period.between(dob, LocalDate.now());
        if (p.getYears() > 0) return p.getYears() + "y " + p.getMonths() + "m";
        return p.getMonths() + " months";
    }

    private static int ageInMonths(LocalDate dob) {
        if (dob == null) return 0;
        return (int) Period.between(dob, LocalDate.now()).toTotalMonths();
    }
}
